### ISSUE TITLE
Problem Statement Completed

### ISSUE THREAD

**Issue by omltcat** [omltcat/turbulent-flow#3]
Hi Dr. Smith, 

Here is the [Problem Statement](https://github.com/omltcat/turbulent-flow/blob/main/docs/ProblemStatementAndGoals/ProblemStatement.pdf). Sorry I didn't assign an issue to you after finishing it last Friday.

Phil

**Comment by smiths** [comment]
Feedback:

- great that you explicitly stated how ChatGPT was used.  In the future, so that the flow of your text isn't interrupted, you can cite ChatGPT, or use a footnote.
- you should give a little more information on who Nikita is (PhD Candidate, Department of Mechanical Engineering, McMaster University).  You should also mention his supervisors

Looks great.  Approved!
