### ISSUE TITLE
SRS Presentation Slides

### ISSUE THREAD

**Issue by omltcat** [omltcat/turbulent-flow#4]
Hello Dr. Smith,

Here are the [slides](https://github.com/omltcat/turbulent-flow/blob/main/docs/SRS/SRS.pptx) ([PDF version here](https://github.com/omltcat/turbulent-flow/blob/main/docs/SRS/SRS-Presentation.pdf)) that I will use tomorrow, if you would like to take a look.
I plan on using the black board for illustration as well. I think that way I can better explain the difference between laminar and turbulent flow, and how the program is going to approximate turbulent flow.

Thanks,
Phil

**Comment by smiths** [comment]
Feedback:

- looks great
- I fully agree with the proposed use of the blackboard (you might want to flick the lights on at the front of the room when using the blackboard)
- Is it conventional to use a superscript for the index number (k)?  A subscript might be less confusing, since the superscript looks like it is a power.
- I feel like there should be additional theoretical models - maybe one for a single eddy and then it is used as part of the summation in your main equation.
- More information on the shape function would be good.  Is this another candidate for a theoretical model, or can the shape function be represented by a type?  What is the type of the shape function?  Is it R -> R? or is it an enumerated set?
- The shape function is the same for all of the eddies?
- I'm not sure your A4 is an assumption that is part of the theory.  Whether or not the theory is usable is external to the documentation of the theory.  I would see A4 instead being documented as a rationale for why the SynthEddy tool is appropriate.

**Comment by omltcat** [comment]
> Feedback:
> 
>     * looks great
Thanks!
> 
>     * I fully agree with the proposed use of the blackboard (you might want to flick the lights on at the front of the room when using the blackboard)
> 
>     * Is it conventional to use a superscript for the index number (k)?  A subscript might be less confusing, since the superscript looks like it is a power.
It was used in the original paper. I plan on just take it as-is and document this use in the SRS.
> 
>     * I feel like there should be additional theoretical models - maybe one for a single eddy and then it is used as part of the summation in your main equation.
The model for one single eddy is essentially the shape function. Which I don't quite fully understand the mathematical details yet and will ask Nikita at some point. 
> 
>     * More information on the shape function would be good.  Is this another candidate for a theoretical model, or can the shape function be represented by a type?  What is the type of the shape function?  Is it R -> R? or is it an enumerated set?
I think for a single eddy, the shape function tells how fast the flow speed should be, depending on location (radial distance) relative to the center of the eddy. Again I need to figure this out with some help.
> 
>     * The shape function is the same for all of the eddies?
I think the idea is that you can have all eddies being the same (apart from their orientations), or have several types of different eddies, with different intensity and shape function (or just different function parameters?). But exactly what types of eddies and their distributions is the work Nikita is doing. So for now user should define several arbitrary types of eddies and the program will just take it as-is.
> 
>     * I'm not sure your A4 is an assumption that is part of the theory.  Whether or not the theory is usable is external to the documentation of the theory.  I would see A4 instead being documented as a rationale for why the SynthEddy tool is appropriate.
Good point.

**Comment by smiths** [comment]
Thank you for your quick reply @omltcat.  Sounds good.
